apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }} #local-nginx-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name}}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: nginx
        ports:
          {{- if eq .Values.env "dev" }}
        - containerPort: 8888
          {{- else }}
        - containerPort: {{ .Values.service.port }}
          {{- end}}
